version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    env_file: .env
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    container_name: foodgram-front
    image: ${DOCKER_LOGIN}/foodgram-front
    volumes:
      - ./frontend/:/app/result_build/

  backend:
    container_name: foodgram-back
    env_file: .env
    image: ${DOCKER_LOGIN}/foodgram-back
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  nginx:
    container_name: foodgram-nginx
    env_file: .env
    image: nginx:1.25.1-alpine
    restart: always
    ports:
      - ${NGINX_PORT}:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
      -
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot